name: Run tests

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/dependabot.yml"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/dependabot.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # The minimum supported version from go.mod, plus the two supported Go releases
        go-version: [1.22.x, oldstable, stable]
        platform: [ubuntu-latest, macos-14]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "${{ matrix.go-version }}"

      # Examples are excluded since they're slow and run in real time
      - name: Run tests
        if: ${{ !(matrix.go-version == 'stable' && matrix.platform == 'ubuntu-latest') }}
        run: go test -v -race $(go list ./... | grep -v /examples)

      - name: Run tests with coverage
        if: ${{ matrix.go-version == 'stable' && matrix.platform == 'ubuntu-latest' }}
        run: go test -v -race -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v /examples)

      - name: Upload coverage reports to Codecov
        if: ${{ matrix.go-version == 'stable' && matrix.platform == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: failsafe-go/failsafe-go
